### ISSUE TITLE
update AllocatePresalePurchase()  to dispatch a transfer event

### ISSUE THREAD

**Issue by lllwvlvwlll** [Moonlight-io/moonlight-ico-template#1]
currently, when deploying presale allocations, the AllocatePresalePurchase() does not dispatch a transfer event which prevents ecosystem tools from identifying allocation of tokens.

**Comment by ghost** [comment]
Due to the way the vesting mechanic works it isn't feasible to be throwing a transfer event during this method. For vesting of tokens to work the source of truth for balance must be balanceOf and BalanceOfVestedAddress

This is by design and won't be changed.
